# Site settings
title: Paper Street 
header-img: img/home-bg.jpg
email: mengdong0427@gmail.com
copyright_name: Dong Meng
author: Dong Meng (孟东)
description: "Dong's personal website"
baseurl: ""
url: "http://mengdong.github.io"
twitter_username: dong__m
github_username:  mengdong
kaggle_username: koalaking
facebook_username: dong.meng.3  
email_username:  mengdong0427@gmail.com
linkedin_username: dong-meng

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-79885047-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hi, I am Dong Meng. My SNS could be found at bottom of this page. You could email me at dongm.datascience@gmail.com"
sidebar-avatar: /img/head.jpg
